init:
	go build -o ../bin/gocoverutil github.com/AlekSi/gocoverutil
	go build -o ../bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
	go build -o ../bin/go-consistent github.com/quasilyte/go-consistent
	go build -o ../bin/reviewdog github.com/reviewdog/reviewdog/cmd/reviewdog
	go build -o ../bin/goimports golang.org/x/tools/cmd/goimports
